// <auto-generated />
using System;
using KlaskApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KlaskApi.Migrations
{
    [DbContext(typeof(TurnierContext))]
    [Migration("20231026094157_AddGruppen")]
    partial class AddGruppen
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KlaskApi.Models.Gruppe", b =>
                {
                    b.Property<long>("GruppeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("GruppeId"));

                    b.Property<string>("Gruppenname")
                        .HasColumnType("text");

                    b.Property<long>("TurnierId")
                        .HasColumnType("bigint");

                    b.HasKey("GruppeId");

                    b.HasIndex("TurnierId");

                    b.ToTable("Gruppen", (string)null);
                });

            modelBuilder.Entity("KlaskApi.Models.Turnier", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("EndDatum")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartDatum")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TurnierTitel")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Turniere", (string)null);
                });

            modelBuilder.Entity("KlaskApi.Models.Gruppe", b =>
                {
                    b.HasOne("KlaskApi.Models.Turnier", "Turnier")
                        .WithMany("Gruppen")
                        .HasForeignKey("TurnierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Turnier");
                });

            modelBuilder.Entity("KlaskApi.Models.Turnier", b =>
                {
                    b.Navigation("Gruppen");
                });
#pragma warning restore 612, 618
        }
    }
}
