// <auto-generated />
using System;
using KlaskApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KlaskApi.Migrations
{
    [DbContext(typeof(TurnierContext))]
    [Migration("20231026083321_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KlaskApi.Models.Turnier", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("EndDatum")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartDatum")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TurnierTitel")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Turniere", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
